#!/usr/bin/env python3
"""Switch all project/* Matter lighting targets between board profiles."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
PROJECT_ROOT = Path(__file__).resolve().parents[1]
BOARDS_DIR = Path(__file__).resolve().parent / "boards"
ACTIVE_FILE = PROJECT_ROOT / ".board-active"

PRODUCTS = (
    "dimmable_light",
    "colortemperature_light",
    "extended_color_light",
    "extended_color_light_strip",
    "onoff_plug",
    "metering_plug",
)

# slcp 中始终移除的板型/芯片相关组件 id（其余从各 profile 动态收集）
STATIC_REMOVABLE_IDS = {
    "brd2703a",
    "brd2703a_a02",
    "brd2703a_config",
    "rf_bm_mg24b1",
    "rf_bm_mg24b1_carrier",
    "rf_bm_mg24b1_config",
    "rf_bm_mg24b2",
    "rf_bm_mg24b2_carrier",
    "rf_bm_mg24b2_config",
    "EFR32MG24B210F1536IM48",
    "EFR32MG24A410F1536IM48",
    "EFR32MG24A420F1536IM48",
}

RAIL_SEQUENCER_FILENAME = "sl_rail_util_sequencer_config.h"
RAIL_PA_TABLES_FILENAME = "sl_rail_util_pa_tables_config.h"

# 含 autoselected_components 的应用 slcp（PWM 类产品）
PWM_APP_SLCP = {
    "matter_thread_soc_dimmable_light_app_freertos.slcp",
    "matter_thread_soc_colortemperature_light_app_freertos.slcp",
    "matter_thread_soc_extended_color_light_app_freertos.slcp",
}

RAIL_SEQUENCER_10DBM = """\
/***************************************************************************//**
 * @file
 * @brief RAIL sequencer image ({label}, {pa_dbm} dBm PA).
 * @note Auto-generated by project/scripts/switch_board.py — do not edit manually.
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_SEQUENCER_H
#define SL_RAIL_UTIL_SEQUENCER_H

#ifdef __cplusplus
extern "C" {{
#endif

#define SL_RAIL_UTIL_SEQUENCER_RUNTIME_IMAGE_SELECTION 0

#define SL_RAIL_UTIL_SEQUENCER_IMAGE RAIL_SEQ_IMAGE_PA_10_DBM

#ifdef __cplusplus
}}
#endif

#endif // SL_RAIL_UTIL_SEQUENCER_H
"""

RAIL_SEQUENCER_20DBM = """\
/***************************************************************************//**
 * @file
 * @brief RAIL sequencer image ({label}, {pa_dbm} dBm PA).
 * @note Auto-generated by project/scripts/switch_board.py — do not edit manually.
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_SEQUENCER_H
#define SL_RAIL_UTIL_SEQUENCER_H

#ifdef __cplusplus
extern "C" {{
#endif

#define SL_RAIL_UTIL_SEQUENCER_RUNTIME_IMAGE_SELECTION 0

#define SL_RAIL_UTIL_SEQUENCER_IMAGE RAIL_SEQ_IMAGE_PA_20_DBM

#ifdef __cplusplus
}}
#endif

#endif // SL_RAIL_UTIL_SEQUENCER_H
"""

RAIL_PA_TABLES_10DBM = """\
/***************************************************************************//**
 * @file
 * @brief PA Tables ({label}, {pa_dbm} dBm PA).
 * @note Auto-generated by project/scripts/switch_board.py — do not edit manually.
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_PA_TABLES_CONFIG_H
#define SL_RAIL_UTIL_PA_TABLES_CONFIG_H

#define SL_RAIL_UTIL_PA_TABLE_HEADER    "sl_rail_util_pa_dbm_powersetting_mapping_table_automode_0_10dbm.h"

#include SL_RAIL_UTIL_PA_TABLE_HEADER

#endif // SL_RAIL_UTIL_PA_TABLES_CONFIG_H
"""

RAIL_PA_TABLES_20DBM = """\
/***************************************************************************//**
 * @file
 * @brief PA Tables ({label}, {pa_dbm} dBm PA).
 * @note Auto-generated by project/scripts/switch_board.py — do not edit manually.
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_PA_TABLES_CONFIG_H
#define SL_RAIL_UTIL_PA_TABLES_CONFIG_H

#define SL_RAIL_UTIL_PA_TABLE_HEADER    "sl_rail_util_pa_dbm_powersetting_mapping_table_20dbm.h"

#include SL_RAIL_UTIL_PA_TABLE_HEADER

#endif // SL_RAIL_UTIL_PA_TABLES_CONFIG_H
"""


def load_profile(board_id: str) -> dict:
    path = BOARDS_DIR / board_id / "profile.yaml"
    if not path.is_file():
        raise SystemExit(f"未找到板型 profile: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def list_boards() -> list[str]:
    return sorted(
        p.name for p in BOARDS_DIR.iterdir() if p.is_dir() and (p / "profile.yaml").is_file()
    )


def read_active_board() -> str | None:
    if not ACTIVE_FILE.is_file():
        return None
    text = ACTIVE_FILE.read_text(encoding="utf-8").strip()
    return text or None


def write_active_board(board_id: str) -> None:
    ACTIVE_FILE.write_text(board_id + "\n", encoding="utf-8")


def collect_removable_ids() -> set[str]:
    """从所有 profile 收集需在 slcp 中替换的组件 id。"""
    ids = set(STATIC_REMOVABLE_IDS)
    for board_id in list_boards():
        profile = load_profile(board_id)
        for key in ("chip_id", "board_id", "board_revision_id", "board_config_id"):
            value = profile.get(key)
            if value:
                ids.add(value)
        for section in ("autoselected_app", "autoselected_bootloader"):
            for entry in profile.get(section) or []:
                entry_id = entry.get("id")
                if entry_id:
                    ids.add(entry_id)
    return ids


def profile_pa_tx_dbm(profile: dict) -> int:
    """返回 profile 对应 PA 发射功率档位（10 或 20）。"""
    pa = profile.get("pa_tx_dbm")
    if pa in (10, 20):
        return pa
    chip = (profile.get("chip_id") or "").upper()
    # A420/B220 等为 19.5 dBm 档，需 PA_20_DBM sequencer
    if "A420" in chip or "B220" in chip or "B120" in chip:
        return 20
    return 10


def is_rf_module_profile(profile: dict) -> bool:
    return str(profile.get("id", "")).startswith("rf_bm_")


def apply_rail_pa_config(config_dir: Path, profile: dict) -> None:
    """按 PA 功率档写入 RAIL sequencer / PA tables，避免 RAIL Assert:83。"""
    config_dir.mkdir(parents=True, exist_ok=True)
    pa_dbm = profile_pa_tx_dbm(profile)
    label = profile.get("label") or profile.get("id", "unknown")
    ctx = {"label": label, "pa_dbm": pa_dbm}

    if pa_dbm == 20:
        sequencer = RAIL_SEQUENCER_20DBM.format(**ctx)
        pa_tables = RAIL_PA_TABLES_20DBM.format(**ctx)
        image = "RAIL_SEQ_IMAGE_PA_20_DBM"
    else:
        sequencer = RAIL_SEQUENCER_10DBM.format(**ctx)
        pa_tables = RAIL_PA_TABLES_10DBM.format(**ctx)
        image = "RAIL_SEQ_IMAGE_PA_10_DBM"

    (config_dir / RAIL_SEQUENCER_FILENAME).write_text(sequencer, encoding="utf-8")
    (config_dir / RAIL_PA_TABLES_FILENAME).write_text(pa_tables, encoding="utf-8")
    print(f"    RAIL PA: {pa_dbm} dBm -> {image}")


def _filter_components(components: list | None, removable_ids: set[str]) -> list:
    if not components:
        return []
    return [c for c in components if c.get("id") not in removable_ids]


def _entry(package: str, comp_id: str) -> dict:
    return {"package": package, "vendor": "silabs", "id": comp_id}


def patch_slcp(slcp_path: Path, profile: dict, removable_ids: set[str]) -> None:
    text = slcp_path.read_text(encoding="utf-8")
    header = ""
    body = text
    if text.startswith("#"):
        parts = text.split("\n", 2)
        if len(parts) >= 2 and parts[1].startswith("#"):
            header = parts[0] + "\n" + parts[1] + "\n"
            body = text[len(header) :]

    data = yaml.safe_load(body) or {}
    for key in ("component", "autoselected_components"):
        data[key] = _filter_components(data.get(key), removable_ids)

    components = data.setdefault("component", [])
    components.append(_entry(profile["board_package"], profile["board_id"]))

    is_bootloader = "bootloader" in slcp_path.parts
    use_autoselected = is_bootloader or slcp_path.name in PWM_APP_SLCP
    if is_rf_module_profile(profile):
        use_autoselected = True

    if use_autoselected:
        if is_bootloader:
            auto = profile.get("autoselected_bootloader") or []
        else:
            auto = profile.get("autoselected_app") or []
        data["autoselected_components"] = list(auto)
    elif "autoselected_components" in data:
        data.pop("autoselected_components")

    slcp_path.write_text(header + yaml.dump(data, default_flow_style=False, sort_keys=False), encoding="utf-8")


def patch_pintool(pintool_path: Path, profile: dict) -> None:
    if not pintool_path.is_file():
        return
    text = pintool_path.read_text(encoding="utf-8")
    text = re.sub(
        r'name="pin_tool\.[^"]+"',
        f'name="{profile["pintool_name"]}"',
        text,
        count=1,
    )
    text = re.sub(
        r'partId="mcu\.arm\.efr32\.mg24\.[^"]+"',
        f'partId="{profile["pintool_part_id"]}"',
        text,
        count=1,
    )
    pintool_path.write_text(text, encoding="utf-8")


def patch_slc_args_json(json_path: Path, profile: dict) -> None:
    if not json_path.is_file():
        return
    data = json.loads(json_path.read_text(encoding="utf-8"))
    data["partOpn"] = profile["part_opn"]
    data["boards"] = profile["slc_args_board"]
    json_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def copy_profile_config(profile_dir: Path, config_dir: Path) -> None:
    src = profile_dir / "config"
    if not src.is_dir():
        return
    config_dir.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        if item.is_file():
            shutil.copy2(item, config_dir / item.name)


def product_paths(product: str) -> tuple[Path, Path, Path]:
    app_dir = PROJECT_ROOT / product / f"{product}_app"
    boot_dir = PROJECT_ROOT / product / "matter_bootloader"
    return app_dir, boot_dir, app_dir / "config"


def switch_product(product: str, profile: dict, removable_ids: set[str]) -> None:
    app_dir, boot_dir, config_dir = product_paths(product)
    profile_dir = BOARDS_DIR / profile["id"]

    for slcp in app_dir.glob("*.slcp"):
        patch_slcp(slcp, profile, removable_ids)
    for slcp in boot_dir.glob("*.slcp"):
        patch_slcp(slcp, profile, removable_ids)

    for pintool in list(app_dir.glob("*.pintool")) + list(boot_dir.glob("*.pintool")):
        patch_pintool(pintool, profile)

    for sub in ("common", "btconf"):
        patch_slc_args_json(config_dir / sub / "slc_args.json", profile)

    copy_profile_config(profile_dir, config_dir)
    apply_rail_pa_config(config_dir, profile)


def switch_board(board_id: str, force: bool = False) -> None:
    boards = list_boards()
    if board_id not in boards:
        raise SystemExit(f"未知板型: {board_id}，可选: {', '.join(boards)}")

    profile = load_profile(board_id)
    active = read_active_board()
    if active == board_id and not force:
        print(f"当前已是板型: {board_id}（使用 --force 可重新应用配置）")
        return

    removable_ids = collect_removable_ids()
    pa_dbm = profile_pa_tx_dbm(profile)

    if active == board_id:
        print(f"强制重新应用板型: {board_id} (PA {pa_dbm} dBm)")
    else:
        print(f"切换板型: {active or '(未设置)'} -> {board_id} (PA {pa_dbm} dBm)")

    for product in PRODUCTS:
        print(f"  更新 {product} ...")
        switch_product(product, profile, removable_ids)

    write_active_board(board_id)
    print(f"完成。已写入 {ACTIVE_FILE.relative_to(REPO)}")
    print("请重新执行 ./build.sh <项目名> 进行 slc generate 与编译。")


def show_status() -> None:
    active = read_active_board() or "(未设置)"
    print(f"当前板型: {active}")
    print("可用板型:")
    for board_id in list_boards():
        profile = load_profile(board_id)
        pa_dbm = profile_pa_tx_dbm(profile)
        chip = profile.get("chip_id", "")
        mark = " *" if board_id == read_active_board() else ""
        print(
            f"  {board_id}: {profile.get('label', '')} | {chip} | "
            f"PA {pa_dbm} dBm | CTUNE {profile.get('hfxo_ctune', '?')}{mark}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="在 project/ 四个产品间切换硬件板型 profile")
    parser.add_argument(
        "board",
        nargs="?",
        choices=list_boards() + ["status"],
        help="目标板型，或 status 查看当前",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="即使当前板型相同也重新应用 profile 与 RAIL PA 配置",
    )
    args = parser.parse_args()

    if args.board is None or args.board == "status":
        show_status()
        return

    switch_board(args.board, force=args.force)


if __name__ == "__main__":
    main()
