/***************************************************************************//**
 * @file
 * @brief PA Tables (BRD2703A Explorer Kit, 10 dBm PA).
 * @note Auto-generated by project/scripts/switch_board.py — do not edit manually.
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_PA_TABLES_CONFIG_H
#define SL_RAIL_UTIL_PA_TABLES_CONFIG_H

#define SL_RAIL_UTIL_PA_TABLE_HEADER    "sl_rail_util_pa_dbm_powersetting_mapping_table_automode_0_10dbm.h"

#include SL_RAIL_UTIL_PA_TABLE_HEADER

#endif // SL_RAIL_UTIL_PA_TABLES_CONFIG_H
