/***************************************************************************//**
 * @file
 * @brief RAIL sequencer image (BRD2703A Explorer Kit, 10 dBm PA).
 * @note Auto-generated by project/scripts/switch_board.py — do not edit manually.
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_SEQUENCER_H
#define SL_RAIL_UTIL_SEQUENCER_H

#ifdef __cplusplus
extern "C" {
#endif

#define SL_RAIL_UTIL_SEQUENCER_RUNTIME_IMAGE_SELECTION 0

#define SL_RAIL_UTIL_SEQUENCER_IMAGE RAIL_SEQ_IMAGE_PA_10_DBM

#ifdef __cplusplus
}
#endif

#endif // SL_RAIL_UTIL_SEQUENCER_H
