#ifndef SL_MATTER_ICD_SERVER_BUILDCONFIG_H
#define SL_MATTER_ICD_SERVER_BUILDCONFIG_H

#define ICD_REPORT_ON_ENTER_ACTIVE_MODE 0
#define ICD_ENFORCE_SIT_SLOW_POLL_LIMIT 0
#define ICD_MAX_NOTIFICATION_SUBSCRIBERS 1
#define CHIP_CONFIG_ENABLE_ICD_LIT 1
#define CHIP_CONFIG_ENABLE_ICD_CIP 1
#define CHIP_CONFIG_ENABLE_ICD_UAT 1

#endif // SL_MATTER_ICD_SERVER_BUILDCONFIG_H
